### ISSUE TITLE
Recognition scores are lower than JS version

### ISSUE THREAD

**Issue by fotiDim** [fe9lix/DollarP_ObjC#1]
I am drawing exactly the same shape ("T") and the recognition scores is most of the times 0 and it is more than 0 it still is way lower that JS equivalent. Any idea why is that happening?

**Comment by s4reea** [comment]
I think i am facing the same issue.
It happens to me when i put a lot of coordinates into a point cloud.
I think i need to narrow down the number of coordinates of each shape to the most important coordinates.
let me know if you found a fix.

EDIT: I noticed that if i have inside the shape 2 strokes or more that are composed of only a DOT this makes it hard to recognize. And only then i get most of the time as 0 score.

**Comment by garrettlarson** [comment]
I think this should improve the recognition scores: https://github.com/fe9lix/DollarP_ObjC/pull/2

**Comment by fe9lix** [comment]
Merged your PR. Thx!
